rewrite release script with tag commit checking

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,27 +1,15 @@
 #!/usr/bin/env sh
 
-# Prepare build target directory
-rm -fr dist/manga-server
-mkdir -p dist/manga-server
+# Check if current commit is tagged, exit if not
+git describe --exact-match > /dev/null 2>&1
+if [ $? != 0 ]; then
+  echo "[ERROR] Building a release artifact is for tagged commit only."
+  echo "exit: 1"
+  exit 1
+fi
 
-composer install --no-dev
-composer dump-autoload --optimize
+# Run build command
+bin/build
 
-# Build frontend artifact
-yarn build
-
-# Copy artifact into dist directory
-cp -r config public src templates vendor dist/manga-server
-
-# Remove php_cs cache
-find dist -type f -name "*.cache" -exec rm {} \;
-
-# Define environment variable
-echo "APP_ENV=prod" > dist/manga-server/.env
-echo "APP_SECRET=$(openssl rand -hex 20)" >> dist/manga-server/.env
-echo "MANGA_ROOT_DIRECTORY=/" >> dist/manga-server/.env
-
-cd dist; zip -r manga-server.$(git describe).zip manga-server; cd ..
-
-# Re-install dependencies
-composer install
+# Package archive, move to dist directory
+cd build; zip -r manga-server.$(git describe).zip manga-server; mv *.zip ../dist/; cd ..
